doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                # configure these for your database server
                url: '%env(resolve:DATABASE_URL)%'
                driver: 'pdo_mysql'
                # IMPORTANT: You MUST configure your server version,
                # either here or in the DATABASE_URL env var (see .env file)
                #server_version: '5.7'
            dhl:
                url: '%env(resolve:DATABASE_DHL_URL)%'
                driver: 'sqlsrv'
                charset: UTF-8
                schema_filter: ~^(?!Estadísticas|Resultados)~
    orm:
        default_entity_manager: default
        auto_generate_proxy_classes: true
        entity_managers:
            default:
                connection: default
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
                auto_mapping: true
                mappings:
                    App:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity'
                        prefix: 'App\Entity'
                        alias: App
            dhl:
                connection: dhl
                mappings:
                    Dhl:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Dhl_Entity'
                        prefix: 'Dhl\Dhl_Entity'
                        alias: Dhl
